import React,{useState} from 'react';
import {SafeAreaView,View,Text,TextInput,Pressable,StyleSheet} from 'react-native';
import * as Haptics from 'expo-haptics';

export default function App(){
 const [take,setTake]=useState('');
 const stamp=async()=>{await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);};
 return <SafeAreaView style={s.safe}><View style={s.page}><Text style={s.logo}>🔥 TAEKS</Text><View style={s.hero}><Text style={s.kicker}>SAY IT. LOCK IT. PROVE IT.</Text><Text style={s.title}>What's your <Text style={s.orange}>take?</Text></Text><Text style={s.sub}>Turn any prediction into a permanent, timestamped receipt.</Text><View style={s.box}><TextInput multiline value={take} onChangeText={setTake} placeholder="Josh Allen wins MVP..." placeholderTextColor="#666" style={s.input}/><Pressable onPress={stamp} style={s.button}><Text style={s.buttonText}>🔥  LOCK IT</Text></Pressable></View></View><Text style={s.section}>YOUR LIVE TAKES</Text><View style={s.card}><Text style={s.tag}>NFL · 2026</Text><Text style={s.cardTitle}>Josh Allen wins NFL MVP</Text><Text style={s.meta}>🔒 TAEKS #A83F91 · LIVE</Text></View></View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0c0c0d'},page:{flex:1,padding:22},logo:{color:'#f5f3ed',fontSize:18,fontWeight:'900',letterSpacing:2},hero:{marginTop:70},kicker:{color:'#888',fontWeight:'800',fontSize:10,letterSpacing:2},title:{color:'#f5f3ed',fontSize:48,fontWeight:'900',lineHeight:50,marginTop:8},orange:{color:'#ff5a1f'},sub:{color:'#999',fontSize:16,marginTop:14,marginBottom:26},box:{backgroundColor:'#171719',borderColor:'#333',borderWidth:1,borderRadius:22,padding:18},input:{height:110,color:'#fff',fontSize:22,fontWeight:'700',textAlignVertical:'top'},button:{backgroundColor:'#ff5a1f',padding:16,borderRadius:14,alignItems:'center'},buttonText:{fontWeight:'900',color:'#16100c'},section:{color:'#ff7042',fontSize:10,fontWeight:'900',letterSpacing:2,marginTop:40,marginBottom:10},card:{backgroundColor:'#161618',borderColor:'#333',borderWidth:1,borderRadius:20,padding:20},tag:{color:'#ff7042',fontSize:10,fontWeight:'900',letterSpacing:2},cardTitle:{color:'#fff',fontSize:28,fontWeight:'900',marginVertical:10},meta:{color:'#777',fontSize:10,fontWeight:'700'}});
